services:
  lb:
    image: haproxy:alpine
    container_name: lb
    cpuset: "0"
    volumes:
      - ./loadbalancers/haproxy/haproxy-unix.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "47MB"

  api1:
    image: ${IMAGE:-villanidev/rinha-de-backend-2026:latest}
    container_name: api1
    cpuset: "1"
    environment:
      SERVER_SOCKET_PATH: /sockets/api1.sock
      APP_VECTOR_SEARCH_INDEX: ivf_pq
      APP_VECTOR_SEARCH_NPROBE: "20"
      APP_VECTOR_SEARCH_CANDIDATES: "10"
      APP_VECTOR_SEARCH_RERANK_ENABLED: "true"
      APP_VECTOR_SEARCH_RERANK_NPROBE: "32"
      APP_VECTOR_SEARCH_RERANK_CANDIDATES: "10"
      APP_FRAUD_DEBUG: "false"
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "147MB"

  api2:
    image: ${IMAGE:-villanidev/rinha-de-backend-2026:latest}
    container_name: api2
    cpuset: "2"
    environment:
      SERVER_SOCKET_PATH: /sockets/api2.sock
      APP_VECTOR_SEARCH_INDEX: ivf_pq
      APP_VECTOR_SEARCH_NPROBE: "20"
      APP_VECTOR_SEARCH_CANDIDATES: "10"
      APP_VECTOR_SEARCH_RERANK_ENABLED: "true"
      APP_VECTOR_SEARCH_RERANK_NPROBE: "32"
      APP_VECTOR_SEARCH_RERANK_CANDIDATES: "10"
      APP_FRAUD_DEBUG: "false"
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "147MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=9m"