services:
  lb:
    image: haproxy:alpine
    cpuset: "0"
    volumes:
      - ./loadbalancers/haproxy/haproxy-unix.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  api1:
    image: ${IMAGE:-villanidev/rinha-de-backend-2026:latest}
    cpuset: "1"
    environment:
      SERVER_SOCKET_PATH: /sockets/api1.sock
      APP_VECTOR__SEARCH_INDEX: ivf_pq
      APP_VECTOR__SEARCH_NPROBE: "1"
      APP_VECTOR__SEARCH_NPROBE__GRAY: "1"
      APP_VECTOR__SEARCH_CANDIDATES: "5"
      APP_VECTOR__SEARCH_RERANK: "true"
      APP_FRAUD_DEBUG: "false"
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"

  api2:
    image: ${IMAGE:-villanidev/rinha-de-backend-2026:latest}
    cpuset: "2"
    environment:
      SERVER_SOCKET_PATH: /sockets/api2.sock
      APP_VECTOR__SEARCH_INDEX: ivf_pq
      APP_VECTOR__SEARCH_NPROBE: "1"
      APP_VECTOR__SEARCH_NPROBE__GRAY: "1"
      APP_VECTOR__SEARCH_CANDIDATES: "5"
      APP_VECTOR__SEARCH_RERANK: "true"
      APP_FRAUD_DEBUG: "false"
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"

volumes:
  sockets:

networks:
  rinha:
    driver: bridge
