services:
  lb:
    #image: nginx:alpine
    image: haproxy:alpine
    volumes:
      # - ./loadbalancers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./loadbalancers/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  api1:
    image: ${IMAGE:-villanidev/rinha-de-backend-2026:latest}
    environment:
      APP_VECTOR__SEARCH_INDEX: ivf_pq
      APP_VECTOR__SEARCH_NPROBE: "64"
      APP_VECTOR__SEARCH_NPROBE__GRAY: "32"
      APP_VECTOR__SEARCH_CANDIDATES: "50"
      APP_VECTOR__SEARCH_RERANK__ENABLED: "false"
      APP_VECTOR__SEARCH_RERANK__NPROBE: "64"
      APP_VECTOR__SEARCH_RERANK__CANDIDATES: "15"
      APP_FRAUD_DEBUG: "false"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  api2:
    image: ${IMAGE:-villanidev/rinha-de-backend-2026:latest}
    environment:
      APP_VECTOR__SEARCH_INDEX: ivf_pq
      APP_VECTOR__SEARCH_NPROBE: "64"
      APP_VECTOR__SEARCH_NPROBE__GRAY: "32"
      APP_VECTOR__SEARCH_CANDIDATES: "50"
      APP_VECTOR__SEARCH_RERANK__ENABLED: "false"
      APP_VECTOR__SEARCH_RERANK__NPROBE: "64"
      APP_VECTOR__SEARCH_RERANK__CANDIDATES: "15"
      APP_FRAUD_DEBUG: "false"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

networks:
  rinha:
    driver: bridge
