# Properties que estavam nos exemplos do Helidon kkk
declarative:
  ignore-incubating: true

# Properties do Helidon WebServer
server:
  port: 8080
  host: 0.0.0.0

# Properties customizadas
app:
  vector-search:
    #index: "brute_force"
    index: "ivf_pq"
    clusters: 4096
    nprobe: 12
    nprobe-gray: 8
    candidates: 50
    rerank: true
  fraud:
    debug: false
