package villani.dev;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import villani.dev.fraud.FraudCheckService;
import villani.dev.fraud.TransactionRequest;
import villani.dev.vectorsearch.embedding.EmbeddingService;
import villani.dev.vectorsearch.index.VectorIndexFactory;
import villani.dev.vectorsearch.retrieval.VectorStore;

import io.helidon.config.Config;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.OffsetDateTime;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

/**
 * Integration test — validates the full pipeline against the canonical example in DETECTION_RULES.md.
 *
 * Requires data.bin to exist (generated by --preprocess). Skipped otherwise.
 *
 * Run with: mvn test -Dintegration.data.bin=data.bin
 * Or just:  mvn test   (skipped if data.bin absent)
 */
class FraudDetectionIntegrationTest {

    private static final Path DATA_BIN = Path.of("data-output/data.bin");
    private static FraudCheckService fraudService;
    private static VectorStore vectorStore;
    private static boolean available;

    @BeforeAll
    static void setup() throws Exception {
        available = Files.exists(DATA_BIN);
        if (!available) {
            System.out.println("[INTEGRATION] data.bin not found — skipping integration tests.");
            return;
        }

        System.out.println("[INTEGRATION] Loading " + DATA_BIN.toAbsolutePath());
        Config config = Config.create();
        VectorIndexFactory factory = new VectorIndexFactory(config);
        vectorStore = new VectorStore(factory);
        vectorStore.load(DATA_BIN);

        EmbeddingService embeddingService = new EmbeddingService();
        fraudService = new FraudCheckService(embeddingService, vectorStore, new villani.dev.health.PerformanceStats(), config);
        System.out.println("[INTEGRATION] VectorStore loaded OK.");
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Test 1: normalization constants match normalization.json
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    void normalizationConstants_matchSpec() {
        if (!available) return;

        float[] norms = vectorStore.getNormalization();
        assertThat("NORM_COUNT", norms.length, is(7));

        // normalization.json: max_amount=10000, max_installments=12, amount_vs_avg_ratio=10,
        //   max_minutes=1440, max_km=1000, max_tx_count_24h=20, max_merchant_avg_amount=10000
        float[] expected = {10000f, 12f, 10f, 1440f, 1000f, 20f, 10000f};
        String[] names = {"max_amount","max_installments","amount_vs_avg_ratio",
                          "max_minutes","max_km","max_tx_count_24h","max_merchant_avg_amount"};
        for (int i = 0; i < expected.length; i++) {
            System.out.printf("[INTEGRATION] norm[%d] %-28s = %.2f  (expected %.2f) %s%n",
                i, names[i], norms[i], expected[i],
                Math.abs(norms[i] - expected[i]) < 0.1f ? "OK" : "MISMATCH !!!");
            assertThat("norms[" + i + "] " + names[i], (double) norms[i], closeTo(expected[i], 0.1));
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Test 2: MCC risk table matches mcc_risk.json
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    void mccRiskTable_matchesSpec() {
        if (!available) return;

        float[] mcc = vectorStore.getMccRisk();
        assertThat("MCC table size", mcc.length, is(10_000));

        int[][] entries = {{5411,15},{5812,30},{5912,20},{5944,45},
                           {7801,80},{7802,75},{7995,85},{4511,35},{5311,25},{5999,50}};
        for (int[] e : entries) {
            float expected = e[1] / 100f;
            System.out.printf("[INTEGRATION] mcc[%d] = %.2f (expected %.2f) %s%n",
                e[0], mcc[e[0]], expected,
                Math.abs(mcc[e[0]] - expected) < 0.01f ? "OK" : "MISMATCH !!!");
            assertThat("mcc[" + e[0] + "]", (double) mcc[e[0]], closeTo(expected, 0.01));
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Test 3: canonical result from DETECTION_RULES.md
    //   tx-1329056812 → approved=true, score=0.0
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    void canonicalPayload_tx1329056812_approved() {
        if (!available) return;

        TransactionRequest tx = new TransactionRequest(
            "tx-1329056812",
            new TransactionRequest.TransactionData(
                41.12f, 2,
                OffsetDateTime.parse("2026-03-11T18:45:53Z").getHour(),
                OffsetDateTime.parse("2026-03-11T18:45:53Z").getDayOfWeek().getValue(),
                OffsetDateTime.parse("2026-03-11T18:45:53Z").toEpochSecond()
            ),
            new TransactionRequest.CustomerData(
                82.24f, 3,
                false   // MERC-016 is in known_merchants → unknownMerchant=false
            ),
            new TransactionRequest.MerchantData("MERC-016", 5411, 60.25f),
            new TransactionRequest.TerminalData(false, true, 29.2331036248f),
            null
        );

        var result = fraudService.checkScore(tx);

        System.out.printf("[INTEGRATION] tx-1329056812: approved=%b score=%.4f%n",
            parseApproved(result), parseScore(result));
        System.out.printf("[INTEGRATION] Expected:      approved=true  score=0.0000%n");

        // DETECTION_RULES.md specifies: score=0.0, approved=true
        assertThat("tx-1329056812 must be approved", parseApproved(result), is(true));
        assertThat("tx-1329056812 score must be 0.0", parseScore(result), closeTo(0.0, 0.01));
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Test 4: accuracy — IVF-PQ must agree with exact KNN on low-ambiguity queries
    //   Fraud payloads (very high-risk profile) must all return score=1.0
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    void highRiskPayloads_returnFraud() {
        if (!available) return;

        // These three payloads from example-payloads.json have very clear fraud profiles:
        // high amount, is_online=1, card_present=0, unknown merchant, high mcc_risk
        TransactionRequest[] fraudulentTx = {
            txHighRisk("tx-fraud-a", 4000f, 8, "2026-03-17T02:00:00Z", 0.85f, 18),
            txHighRisk("tx-fraud-b", 6000f, 12, "2026-01-15T03:00:00Z", 0.80f, 20),
            txHighRisk("tx-fraud-c", 8000f, 10, "2026-05-20T01:00:00Z", 0.75f, 15),
        };

        System.out.println("[INTEGRATION] High-risk payload accuracy test:");
        for (TransactionRequest tx : fraudulentTx) {
            var result = fraudService.checkScore(tx);
            System.out.printf("[INTEGRATION]   %s → approved=%b score=%.4f%n",
                tx.id(), parseApproved(result), parseScore(result));
            assertThat(tx.id() + " should be denied (high-risk fraud profile)",
                parseApproved(result), is(false));
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Test 5: low-risk payloads must return approved
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    void lowRiskPayloads_returnApproved() {
        if (!available) return;

        // Classic legitimate profile: low amount, offline, card present, known merchant, low mcc
        TransactionRequest[] legitimateTx = {
            txLowRisk("tx-legit-a", 50f,  "2026-03-11T14:00:00Z"),
            txLowRisk("tx-legit-b", 30f,  "2026-03-11T10:30:00Z"),
            txLowRisk("tx-legit-c", 80f,  "2026-03-11T16:00:00Z"),
        };

        System.out.println("[INTEGRATION] Low-risk payload accuracy test:");
        for (TransactionRequest tx : legitimateTx) {
            var result = fraudService.checkScore(tx);
            System.out.printf("[INTEGRATION]   %s → approved=%b score=%.4f%n",
                tx.id(), parseApproved(result), parseScore(result));
            assertThat(tx.id() + " should be approved (low-risk legit profile)",
                parseApproved(result), is(true));
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Test 6: index has expected label distribution (~30% fraud in dataset)
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    void labelDistribution_isReasonable() {
        if (!available) return;

        byte[] labels = vectorStore.getIndexLabels();
        assertThat("labels must not be null", labels, notNullValue());
        assertThat("must have 3 million vectors", labels.length, is(3_000_000));

        long fraudCount = 0;
        for (byte b : labels) if (b == 1) fraudCount++;
        double fraudRate = (double) fraudCount / labels.length;

        System.out.printf("[INTEGRATION] Label distribution: %d fraud / %d total = %.1f%% fraud%n",
            fraudCount, labels.length, fraudRate * 100);

        // Dataset should have fraud rate between 5% and 50% to be meaningful
        assertThat("fraud rate must be between 5% and 50%", fraudRate, allOf(greaterThan(0.05), lessThan(0.50)));
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Helpers
    // ──────────────────────────────────────────────────────────────────────────

    // ── response helpers ─────────────────────────────────────────────────────

    private static boolean parseApproved(String result) {
        return result.contains("\"approved\":true");
    }

    private static double parseScore(String result) {
        int idx = result.indexOf("\"fraud_score\":");
        int start = idx + "\"fraud_score\":".length();
        int end = result.indexOf('}', start);
        return Double.parseDouble(result.substring(start, end));
    }

    private static TransactionRequest txHighRisk(String id, float amount, int installments,
                                                  String requestedAt, float mccRisk, int txCount24h) {
        // Find a mcc that has the requested risk level (approximate)
        int mccCode = mccRisk >= 0.80f ?  7801  : mccRisk >= 0.75f ?  7802  :  7995;
        OffsetDateTime at = OffsetDateTime.parse(requestedAt);
        long txEpoch = at.toEpochSecond();
        return new TransactionRequest(
            id,
            new TransactionRequest.TransactionData(amount, installments,
                at.getHour(), at.getDayOfWeek().getValue(), txEpoch),
            new TransactionRequest.CustomerData(amount * 0.1f, txCount24h, false), // MERC-KNOWN is known
            new TransactionRequest.MerchantData("MERC-UNKNOWN-999", mccCode, amount * 0.05f),
            new TransactionRequest.TerminalData(true, false, 900f),   // online, no card, far
            new TransactionRequest.LastTransactionData(
                txEpoch - 120,   // 2 minutes ago = suspicious
                850f             // 850 km from last tx
            )
        );
    }

    private static TransactionRequest txLowRisk(String id, float amount, String requestedAt) {
        OffsetDateTime at = OffsetDateTime.parse(requestedAt);
        return new TransactionRequest(
            id,
            new TransactionRequest.TransactionData(amount, 1,
                at.getHour(), at.getDayOfWeek().getValue(), at.toEpochSecond()),
            new TransactionRequest.CustomerData(amount * 1.5f, 2, false), // MERC-016 is known
            new TransactionRequest.MerchantData("MERC-016", 5411, amount * 1.2f),
            new TransactionRequest.TerminalData(false, true, 5f),   // offline, card present, near home
            null
        );
    }
}
