Args=--initialize-at-build-time=io.helidon.service.registry.Dependency$BuilderBase$DependencyImpl \
-O3 \
-H:-ReduceImplicitExceptionStackTraceInformation \
-R:MaximumHeapSizePercent=80 \
-march=x86-64-v3 \
-R:+VerboseGC